- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.dhupar.xyz:444
        description: "Media player"
        widget:
          type: jellyfin
          key: "{{HOMEPAGE_FILE_JELLYFIN_KEY}}"
          url: http://127.0.0.1:8096
          enableBlocks: true
          enableNowPlaying: true
- Monitoring:
    - Network:
        widget:
          type: glances
          url: http://host.containers.internal:61208
          metric: network:enp1s0f0
          chart: true
- Services:
    - Vaultwarden:
        icon: bitwarden.svg
        href: https://pass.dhupar.xyz:444
        description: "Password manager"
    - Traefik:
        icon: traefik.svg
        href: https://traefik.dhupar.xyz:444
        description: "Reverse proxy"
