name: Configure Server

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '01 13 * * *'

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  VPS_DEPLOY_USER: ${{ secrets.VPS_DEPLOY_USER }}
  VPS_DEPLOY_HOST: ${{ secrets.VPS_DEPLOY_HOST }}

jobs:
  playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Connect to Tailnet
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.54.1

      # TODO: switch to tailscale ssh
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          chmod 0700 ~/.ssh
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY")

      # time nixos-rebuild switch --show-trace
      # ssh -o "StrictHostKeyChecking no" rishi@100.115.162.66 "
      - name: Switch to latest generation
        run: |
          mkdir -p ~/.ssh/
          chmod 0700 ~/.ssh
          eval $(ssh-agent -s)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          ssh-add -l
          ssh -vv -o "StrictHostKeyChecking no" rishi@100.115.162.66 "
            cd ~/${{ github.event.repository.name }}/
            git fetch && git reset --hard $(git rev-parse HEAD)
            time nixos-rebuild build --show-trace
            "
      
